### ISSUE TITLE
Bug: Env variable BASEURL seem to be overwritten / not read

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#870]
### Description of the bug

In CI: Prior to deploying github-pages, Docusauros is built with config based on env variables. 
The env variable `BASEURL` is strangely enough not read or being overwritten somehow:

Original setup:

workflow-deploy-docs.yml:
```
      - name: 'Build'
        run: pnpm turbo build --filter=docs --filter=storybook
        env:
          URL: 'https://digdir.github.io'
          BASEURL: '/dialogporten-frontend/' 
```

docusauros.config.ts:
```
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: process.env.BASEURL || '/',
```

As a temporary work-around, the default value is switched to the necessary `/dialogporten-frontend/` in order to work for https://digdir.github.io/dialogporten-frontend/ 

  

### Steps To Reproduce

cf. doc above, only reproducable through Github actions
